name: Deploy to AWS Lambda

on:
  workflow_run:
    workflows: ["Install dependencies"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: af-south-1

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name tebogoMotibanaSampleApi --zip-file fileb://tebogoMotibanaSampleApi-33868242-14d4-40f5-a97c-f8cde48de772.zip


     

